### ISSUE TITLE
Bug when packing a module with its target model equal to 7

### ISSUE THREAD

**Issue by crushedice2000** [mefistotelis/phantom-firmware-tools#51]
When I try to pack (append) a module whose target numeration end in 07, the resulting firmware package stores that module with a wrong numeration (exactly, it ends in 00).

I don't consider necessary to add any file to reproduce the issue, as it can be easily tested by unpacking a known firmware, editing manually one of the generated `.ini` files to change the target numeration so it ends with 07 and repacking it. Once this is done, is easy to spot the bug by comparing the result with the original file.

To check the headers of the DJI firmware packages, I've already developed an incomplete (but working for this check) Kaitai Struct definition attached below. It can be used online on the online kaitai [IDE](https://ide.kaitai.io/)
```

meta:
  id: dji_firmware
  file-extension: bin
  endian: le
  license: GPLv2
seq:
  - id: magic
    contents: [0x78, 0x56, 0x34, 0x12,] # Per-byte decrements of 0x22
  - id: version
    type: u2
  - id: header_length
    type: u2
  - id: timestamp
    type: u4
  - id: manufacturer
    type: str
    size: 16
    encoding: utf-8
  - id: model
    type: str
    size: 16
    encoding: utf-8
  - id: entry_count
    type: u2
  - id: latest_version
    size: 4
    process: xor(timestamp) #  FIXME: I don't know how to simultanoulsy xor the magic value to the timestamp
  - id: rollback_version
    size: 4
    process: xor(timestamp)  #  FIXME: I don't know how to simultanoulsy xor the magic value to the timestamp
  - id: padding
    size: 10
  - id: entry
    type: entry_header
    repeat: expr
    repeat-expr: entry_count
types:
  entry_header:
    seq:
      - id: target
        type: u1
      - id: spcoding
        type: u1
      - id: reserved2
        type: u2
      - id: version
        type: u4
      - id: data_offset
        type: u4
      - id: data_length
        type: u4
      - id: decrypted_data_length
        type: u4
      - id: data_md5
        size: 16
      - id: decrypted_data_md5
        size: 16
 
```
